[build]
  command = "pnpm install --no-frozen-lockfile && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200


