[build]
  base = "portfolio-frontend"
  command = "pnpm install --no-frozen-lockfile && npm run build"
  publish = "portfolio-frontend/out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200


